export const data = [
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
  {
    name: "NAsir",
    email: "elnas@gmail.com",
    drop: [],
    text: "This is a test to see something",
    check: false,
  },
];
